export const config = {
    RPC_URL: 'https://chtd-rpc.skynetvalidators.com',
    REST_URL: 'https://api-rpc.skynetvalidators.com',
    EXPLORER_URL: 'https://chronic.zenscan.io',
    STAKING_URL: 'https://try-2.vercel.app/stake',
    NETWORK_NAME: 'Chronic',
    NETWORK_TYPE: 'mainnet',
    CHAIN_ID: 'morocco-1',
    CHAIN_NAME: 'Morocco-1',
    COIN_DENOM: 'CHT',
    COIN_MINIMAL_DENOM: 'ucht',
    COIN_DECIMALS: 6,
    FEE_CURRENCY: 'CGAS',
    PREFIX: 'chronic',
    COIN_TYPE: 118,
    COINGECKO_ID: 'chronic',
    GAS_PRICE_STEP_LOW: 0.001,
    GAS_PRICE_STEP_AVERAGE: 0.01,
    GAS_PRICE_STEP_HIGH: 0.05,
    FEATURES: ['ibc-transfer', 'ibc-go'],
};
